#!/bin/bash
#

# Generated by CHARMM-GUI (http://www.charmm-gui.org) v3.7
#
# This folder contains a pre-optimized PDB structure and OpenMM inputs.
# All input files were optimized for OpenMM v6.2 or above, so lower version of OpenMM can cause some errors.
# You can get the latest development version of OpenMM at the git repository:
# https://github.com/pandegroup/openmm

# INPUTS
# 1 --> gpus to run the simulations

# Input file prefix
init=step3_input


# Check if any step7*.inp files exist
if ls step4*.rst &> /dev/null; then
    # If files exist, find the highest numbered file
    cnt=$(ls -1 step4*.rst | sort -V | tail -1 | cut -d '_' -f1 | cut -d '.' -f2)
    cnt=$(( $cnt + 1 ))
else
    # If no files exist, set cnt to 1
    cnt=1
fi

echo "Equilibration cnt is: $cnt"

while [ ${cnt} -le 2 ]
do
	pcnt=$(( $cnt - 1 ))
	istep=step4.${cnt}_equilibration
	pstep=step4.${pcnt}_equilibration

	if [ $cnt == 1 ]; then
		input_param="-ff amber -p ${init}.parm7 -c ${init}.rst7"
	else
		input_param="-ff amber -p ${init}.parm7 -c ${init}.rst7 -irst ${pstep}.rst"
	fi
	python -u utils/openmm_run.py -i ${istep}.inp ${input_param} -orst ${istep}.rst -ochk ${istep}.chk -odcd ${istep}.dcd > ${istep}.out

    	cnt=$(( $cnt + 1 ))
done


######################################### PRODUCTION PIPELINE #########################################

prod_prefix=step5_production
prod_step=step5

# Extract nstout and dt from the inp file of production
inp_file=${prod_prefix}.inp
dt=$(awk '/^dt[[:space:]]*=/{print $3}' "$inp_file")
nstout=$(awk '/^nstout[[:space:]]*=/{print $3}' "$inp_file")
target_ns=$(awk '/^Target_ns[[:space:]]*=/{print $3}' "$inp_file")
# Sanity check
if [[ -z "$dt" || -z "$nstout" ]]; then
    echo "Error: Failed to extract dt or nstout from $inp_file"
    exit 1
fi

# Compute how many steps correspond to 1 ns
steps_per_ns=$(echo "1000 / $dt" | bc)                # 1000 ps / 0.002 ps = 500000 steps/ns
total_steps=$(echo "$target_ns * $steps_per_ns" | bc) # Total steps to run

# Count total lines in all step5_*.out files (1 line per nstout steps)
total_lines=$(cat ${prod_step}_*.out 2>/dev/null | wc -l)
completed_steps=$((total_lines * nstout))


# Check if any step5*.chk files exist
if ls $prod_step*.chk &> /dev/null; then
    # If files exist, find the highest numbered file
    cnt=$(ls -1 $prod_step*.chk | sort -V | tail -1 | cut -d '_' -f2 | cut -d '.' -f1)
    cnt=$(( $cnt + 1 ))
else
    # If no files exist, set cnt to 1
    cnt=1
fi
echo "Starting at run count $cnt, completed_steps: $completed_steps / $total_steps"

# The OpenMM check point file (.chk) cannot be used in a different machine environment.
# So please make sure if you are using the same GPU and CUDA version of machine while doing additional

# Run until you've simulated the desired number of steps
while [ "$completed_steps" -lt "$total_steps" ]
do
    pcnt=$(($cnt - 1))
    istep=${prod_step}_${cnt}
    pstep=${prod_step}_${pcnt}

    if [ $cnt == 1 ];then
       pstep=step4.2_equilibration
    fi

	if [ -f "${pstep}.chk" ]; then
		echo "Checkpoint exists: ${pstep}.chk"
		input_param="-ff amber -p ${init}.parm7 -c ${init}.rst7 -ichk ${pstep}.chk"
	else
		echo "Checkpoint does not exist, resuming from: ${pstep}.rst"
		input_param="-ff amber -p ${init}.parm7 -c ${init}.rst7 -irst ${pstep}.rst"

    echo ">>> Running $istep..."
    python -u utils/openmm_run.py -i ${prod_prefix}.inp ${input_param} -orst ${istep}.rst -ochk ${istep}.chk -odcd ${istep}.dcd -gpu $1 > ${istep}.out

    echo ">>> Checking if ${istep}.dcd file exists" 
    if [ ! -s ${istep}.dcd ]; then
    	echo "ERROR: ${istep}.dcd was not created or is empty. Exiting."
    	exit 1
    fi

    # Update counters after the run
    cnt=$((cnt + 1))
    total_lines=$(cat ${prod_step}_*.out 2>/dev/null | wc -l)
    completed_steps=$((total_lines * nstout))
done

